name: lint

on: push

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: nodenv/actions/node-version@v2.0.10
        id: nodenv

      - uses: actions/setup-node@v2.5.1
        with:
          node-version: ${{ steps.nodenv.outputs.node-version }}

      - uses: pnpm/action-setup@v2.2.1
        id: pnpm-install
        with:
          version: 7.0.1
          run_install: false

      - name: get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"

      - name: restore install cache
        uses: actions/cache@v3
        id: cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: pnpm-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: pnpm-

      - name: install dependencies
        run: pnpm install

      - name: run lint
        run: pnpm run lint:ci
